name: storage_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_scale_tap: ^1.0.5
  google_fonts: ^4.0.4
  iconsax: ^0.0.8
  percent_indicator: ^4.2.3
  riverpod: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/start_page_icons.png
