name: storage_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_scale_tap: ^1.0.5
  google_fonts: ^4.0.4
  iconsax: ^0.0.8
  percent_indicator: ^4.2.3
  riverpod: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/start_page_icons.png
    - assets/images/folder.png
    - assets/images/other.png
    - assets/images/apps.png
    - assets/images/images.png
    - assets/images/documents.png
    - assets/images/audio.png
    - assets/images/videos.png
    - assets/images/bigfile1.jpg
    - assets/images/bigfile2.jpg
    - assets/images/bigfile3.jpg
    - assets/images/bigfile4.jpg
    - assets/images/bigfile5.jpg
    - assets/images/bigfile6.jpg
    - assets/files_icons/heic.png
    - assets/files_icons/pdf.png
    - assets/files_icons/xls.png
    - assets/files_icons/video.png
